using UnityEngine;
namespace GetThisRock
{
    [DefaultExecutionOrder(-50)]
    public sealed class GameHUD : MonoBehaviour
    {
        public ContractManager contracts; public PlayerWallet wallet; public PlayerInteraction interaction; public PlayerEquipment equipment; public FirstPersonPresentation presentation;
        bool tabletOpen=true; int page; Vector2 scroll; string notice="Empieza con las manos. Acepta un contrato pequeño.";
        GUIStyle title,body,small,button; Font font;
        public bool TabletOpen=>tabletOpen;
        void Start(){if(interaction!=null)equipment=interaction.equipment;SetTablet(true);}
        public void SetTablet(bool open){tabletOpen=open;if(interaction!=null){interaction.ReleaseObjects();interaction.input.SetUIBlocked(open);}if(presentation!=null)presentation.TabletOpen=open;}
        public bool AcceptFromTablet(int index){if(contracts==null||contracts.catalog==null||index<0||index>=contracts.catalog.Length)return false;bool ok=contracts.TryAccept(contracts.catalog[index]);notice=contracts.LastMessage;if(ok)SetTablet(false);return ok;}
        public bool ConfirmDelivery(){if(contracts==null)return false;bool ok=contracts.TryFinish();notice=contracts.LastMessage;if(ok){page=0;scroll=Vector2.zero;SetTablet(true);}return ok;}
        void Update(){if(interaction==null||interaction.input==null)return;if(interaction.input.InventoryPressed){page=2;SetTablet(true);}else if(interaction.input.TabletPressed)SetTablet(!tabletOpen);if(interaction.input.ConfirmPressed)ConfirmDelivery();}
        void Styles(){if(title!=null)return;font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");if(font!=null&&font.material!=null&&font.material.mainTexture!=null)font.material.mainTexture.filterMode=FilterMode.Bilinear;title=Style(26,FontStyle.Bold);body=Style(18,FontStyle.Normal);small=Style(15,FontStyle.Normal);button=new GUIStyle(GUI.skin.button){font=font,fontSize=17,wordWrap=true};}
        GUIStyle Style(int size,FontStyle style){var s=new GUIStyle(GUI.skin.label){font=font,fontSize=size,fontStyle=style,wordWrap=true};s.normal.textColor=Color.white;return s;}
        static void Panel(Rect r,Color c){var old=GUI.color;GUI.color=c;GUI.DrawTexture(r,Texture2D.whiteTexture);GUI.color=old;}
        void OnGUI(){Styles();var previous=GUI.matrix;if(contracts==null||wallet==null||interaction==null||equipment==null||contracts.progression==null||interaction.inventory==null){GUI.Label(new Rect(20,20,700,100),"Cargando componentes de Rock Co.",body);return;}if(tabletOpen){if(presentation!=null&&!presentation.IsReady)return;Rect r=presentation!=null?presentation.ScreenRect():new Rect(30,30,Screen.width-60,Screen.height-60);GUI.matrix=Matrix4x4.TRS(new Vector3(r.x,r.y,0),Quaternion.identity,new Vector3(r.width/960,r.height/600,1));DrawTablet();}else{float s=Mathf.Min(Screen.width/960f,Screen.height/640f);GUI.matrix=Matrix4x4.TRS(new Vector3((Screen.width-960*s)/2,(Screen.height-640*s)/2,0),Quaternion.identity,Vector3.one*s);DrawHUD();}GUI.matrix=previous;}
        void DrawTablet(){Panel(new Rect(0,0,960,600),new Color(.035f,.055f,.075f));GUI.Label(new Rect(24,15,510,42),"ROCK CO. / OPERACIONES",title);GUI.Label(new Rect(545,18,390,34),$"${wallet.Money}  ·  NIVEL {contracts.progression.Level}",body);string[] tabs={"Contratos","Tienda","Inventario","Mejoras"};for(int i=0;i<4;i++)if(GUI.Button(new Rect(24+i*162,69,154,40),tabs[i],button)){page=i;scroll=Vector2.zero;}if(GUI.Button(new Rect(790,69,145,40),"Cerrar [Tab]",button))SetTablet(false);GUI.Label(new Rect(24,119,910,48),GameSave.LastError??notice,small);if(page==0)DrawContracts();else if(page==1)DrawShop();else if(page==2)DrawInventory();else DrawUpgrades();DrawXP(new Rect(24,548,560,18));GUI.Label(new Rect(595,542,340,32),"Guardado automático · I: inventario",small);}
        void DrawXP(Rect r){var p=contracts.progression;Panel(r,new Color(.04f,.05f,.07f));Panel(new Rect(r.x,r.y,r.width*p.LevelProgress,r.height),new Color(.2f,.72f,.42f));GUI.Label(new Rect(r.x+7,r.y-3,r.width,25),$"XP nivel {p.Level}: {p.CurrentLevelXP}/{p.NextLevelXP}",small);}
        void DrawContracts(){if(contracts.catalog==null||contracts.catalog.Length==0){GUI.Label(new Rect(24,180,900,100),"No hay contratos cargados.",body);return;}scroll=GUI.BeginScrollView(new Rect(24,174,912,355),scroll,new Rect(0,0,890,contracts.catalog.Length*112));for(int i=0;i<contracts.catalog.Length;i++){var c=contracts.catalog[i];if(c==null)continue;float y=i*112;Panel(new Rect(0,y,884,103),new Color(.08f,.12f,.16f));GUI.Label(new Rect(14,y+5,620,30),$"{c.displayName} · ${c.reward} · {c.experienceReward} XP",body);GUI.Label(new Rect(14,y+37,620,62),$"Nivel {c.requiredLevel} · {c.rocks.Length} rocas · {c.scenario}\n{c.description}",small);GUI.enabled=contracts.IsUnlocked(c)&&!contracts.HasActiveJob;if(GUI.Button(new Rect(650,y+20,218,60),!contracts.IsUnlocked(c)?$"Requiere nivel {c.requiredLevel}":contracts.HasActiveJob?"Contrato en curso":"Aceptar contrato",button))AcceptFromTablet(i);GUI.enabled=true;}GUI.EndScrollView();if(contracts.State==ContractState.ReadyToFinish&&GUI.Button(new Rect(620,508,295,34),"Terminar y cobrar [Enter]",button))ConfirmDelivery();}
        void DrawShop(){if(equipment.shop==null)return;scroll=GUI.BeginScrollView(new Rect(24,174,912,355),scroll,new Rect(0,0,890,equipment.shop.Length*125));for(int i=0;i<equipment.shop.Length;i++){var t=equipment.shop[i];if(t==null)continue;float y=i*125;Panel(new Rect(0,y,884,115),new Color(.08f,.12f,.16f));GUI.Label(new Rect(14,y+7,590,28),$"{t.displayName} · ${t.price} · 1 espacio",body);GUI.Label(new Rect(14,y+39,600,65),t.description,small);bool owned=equipment.Owns(t.kind),full=interaction.inventory.Used >= interaction.inventory.Capacity;GUI.enabled=!owned&&!full&&wallet.Money>=t.price;if(GUI.Button(new Rect(645,y+26,220,58),owned?"Comprada para siempre":full?"Inventario lleno":wallet.Money<t.price?"Saldo insuficiente":"Comprar",button)){equipment.TryBuy(t);notice=$"{t.displayName} guardada para siempre.";}GUI.enabled=true;}GUI.EndScrollView();}
        void DrawInventory(){GUI.Label(new Rect(24,172,900,34),$"{interaction.inventory.Used}/{interaction.inventory.Capacity} espacios · Las manos no ocupan espacio [F]",body);scroll=GUI.BeginScrollView(new Rect(24,211,912,318),scroll,new Rect(0,0,890,interaction.inventory.Capacity*68));for(int i=0;i<interaction.inventory.Capacity;i++){var slot=interaction.inventory.Slots[i];float y=i*68;Panel(new Rect(0,y,884,58),new Color(.08f,.12f,.16f));GUI.Label(new Rect(14,y+13,500,32),$"[{i+1}] {slot.Label}",body);GUI.enabled=!slot.IsEmpty;if(GUI.Button(new Rect(645,y+7,220,43),"Seleccionar",button)){interaction.inventory.Select(i);SetTablet(false);}GUI.enabled=true;}GUI.EndScrollView();}
        void DrawUpgrades(){var stats=equipment.stats;UpgradeRow(174,"Mochila",$"Espacios: {interaction.inventory.Capacity}/{PlayerInventory.MaximumCapacity}",interaction.inventory.NextUpgradeCost,interaction.inventory.Capacity < PlayerInventory.MaximumCapacity,()=>equipment.TryUpgradeInventory());UpgradeRow(286,"Velocidad",$"Nivel {stats.speedLevel}/5 · Movimiento {stats.MoveSpeed:0.0}",stats.SpeedCost,stats.CanImproveSpeed,()=>equipment.TryUpgradeSpeed());UpgradeRow(398,"Fuerza",$"Nivel {stats.carryLevel}/5 · Carga {stats.CarryMass:0} kg",stats.CarryCost,stats.CanImproveCarry,()=>equipment.TryUpgradeCarry());}
        void UpgradeRow(float y,string name,string value,int cost,bool available,System.Func<bool> buy){Panel(new Rect(24,y,912,96),new Color(.08f,.12f,.16f));GUI.Label(new Rect(40,y+10,560,30),name,body);GUI.Label(new Rect(40,y+47,560,30),value,small);GUI.enabled=available&&wallet.Money>=cost;if(GUI.Button(new Rect(667,y+18,250,58),available?$"Mejorar · ${cost}":"Máximo",button)){if(buy())notice=$"Mejora de {name} comprada.";}GUI.enabled=true;}
        void DrawHUD(){Panel(new Rect(16,16,690,158),new Color(.03f,.05f,.07f,.94f));GUI.Label(new Rect(28,23,655,34),$"ROCK CO.  ${wallet.Money}  ·  NIVEL {contracts.progression.Level}",title);DrawXP(new Rect(28,61,360,16));GUI.Label(new Rect(28,87,650,75),contracts.HasActiveJob?$"{contracts.DeliveredCount}/{contracts.TotalCount} rocas entregadas\n"+(contracts.State==ContractState.ReadyToFinish?"Todo listo. Pulsa ENTER para cobrar.":"Rompe, carga o empuja las rocas hasta ENTREGA."):notice,body);GUI.Label(new Rect(474,307,24,28),"+",body);GUI.Label(new Rect(195,380,580,70),interaction.Prompt,body);if(interaction.Effort>.01f)GUI.Label(new Rect(365,450,300,30),$"Esfuerzo · {interaction.Effort*100:0}%",body);int cap=interaction.inventory.Capacity;for(int i=0;i<cap;i++){int row=i/4,col=i%4;var r=new Rect(116+col*184,490+row*55,176,49);Panel(r,interaction.inventory.SelectedIndex==i?new Color(.23f,.4f,.38f):new Color(.04f,.07f,.1f,.95f));GUI.Label(new Rect(r.x+8,r.y+7,160,36),$"[{i+1}] {interaction.inventory.Slots[i].Label}",small);}GUI.Label(new Rect(24,604,920,30),"F: manos · E: recoger/usar · G: soltar · Q: lanzar roca · Clic: empujar/golpear · Tab: tablet · Enter: cobrar",small);}
    }
}


